import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from './components/navbar';
import 'bootstrap-icons/font/bootstrap-icons.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} 

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body className=" md:mt-3 md:mb-3 font-montserrat">
        <Navbar />
        <main className="">
          {children}
        </main>
       
      </body>
    </html>
  )
}
